Repository googleinterns/blueprint-step-2020, pull requests merged in 2020-08, with the labels that each got.

#121 Create User Interface for Assign Panel
  src/main/java/com/google/sps/model/AuthenticationVerifier.java
  src/main/webapp/assets/assign.png
  src/main/webapp/index.html
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/abstracts/_variables.css
  src/main/webapp/style/base/_typography.css
  src/main/webapp/style/components/_button-1-of-2.css
  src/main/webapp/style/components/_button-circle.css
  src/main/webapp/style/components/_panel.css
Labels: cla: yes, size/L

#134 Remove double authentication calls
  README.md
  src/main/webapp/auth.js
Labels: bug, cla: yes, size/M

#112 Create servlet for assign panel
  src/main/java/com/google/sps/model/ActionableMessage.java
  src/main/java/com/google/sps/model/GmailClient.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
  src/main/java/com/google/sps/model/GmailResponseHelperImpl.java
  src/main/java/com/google/sps/servlets/GmailActionableEmailsServlet.java
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/main/java/com/google/sps/utility/ServletUtility.java
  src/test/java/GmailActionableEmailsServletTest.java
  src/test/java/GmailUtilityTest.java
  src/test/java/ServletUtilityTest.java
Labels: cla: yes, size/XL

#119 Create simple client side implementation of Assign Servlet
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/utilities.js
Labels: cla: yes, size/M

#125 UI for the settings of the Assign Panel
  src/main/webapp/assets/checkbox-selected.png
  src/main/webapp/assets/checkbox-unselected.png
  src/main/webapp/assets/settings-selected.png
  src/main/webapp/assets/settings-unselected.png
  src/main/webapp/assignPanelStyle.js
  src/main/webapp/index.html
  src/main/webapp/panelStyle.js
  src/main/webapp/script.js
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/abstracts/_variables.css
  src/main/webapp/style/base/_base.css
  src/main/webapp/style/base/_typography.css
  src/main/webapp/style/components/_button-1-of-2.css
  src/main/webapp/style/components/_button-circle.css
  src/main/webapp/style/components/_panel.css
Labels: cla: yes, size/L

#118 Implement Locations Utility class
  src/main/java/com/google/sps/utility/LocationsUtility.java
  src/test/java/LocationsUtilityTest.java
Labels: cla: yes, size/L

#138 Authentication refactor to get user email
  src/main/java/com/google/sps/model/AuthenticatedHttpServlet.java
  src/main/java/com/google/sps/model/AuthenticationVerifier.java
  src/main/java/com/google/sps/model/AuthenticationVerifierImpl.java
  src/test/java/AuthenticatedHttpServletTest.java
  src/test/java/AuthenticatedServletTestBase.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#99 Initial implementation of the calendar panel for the MVP.
  src/main/java/com/google/sps/data/CalendarSummaryResponse.java
  src/main/java/com/google/sps/data/TimeHourMin.java
  src/main/java/com/google/sps/model/CalendarClient.java
  src/main/java/com/google/sps/model/CalendarClientImpl.java
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/utility/DateInterval.java
  src/main/java/com/google/sps/utility/FreeTimeUtility.java
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/CalendarServletTest.java
Labels: cla: yes, enhancement, size/XL

#136 Implement Geocoding client
  src/main/java/com/google/sps/exceptions/GeocodingException.java
  src/main/java/com/google/sps/model/GeocodingClient.java
  src/main/java/com/google/sps/model/GeocodingClientFactory.java
  src/main/java/com/google/sps/model/GeocodingClientImpl.java
  src/main/java/com/google/sps/utility/GeocodingResultUtility.java
  src/test/java/GeocodingResultUtilityTest.java
Labels: cla: yes, size/L

#144 Refactor Geocoding for Go panel
  src/main/java/com/google/sps/model/GeocodingClient.java
  src/main/java/com/google/sps/model/GeocodingClientImpl.java
  src/main/java/com/google/sps/utility/GeocodingResultUtility.java
  src/test/java/GeocodingResultUtilityTest.java
Labels: cla: yes, size/L

#145 Refactor Places for Go panel
  src/main/java/com/google/sps/model/PlacesClient.java
  src/main/java/com/google/sps/model/PlacesClientImpl.java
  src/main/java/com/google/sps/utility/PlacesResultUtility.java
  src/test/java/PlacesResultUtilityTest.java
Labels: cla: yes, size/M

#140 Default values for gmail and tasks
  src/main/webapp/index.html
  src/main/webapp/populateData.js
Labels: cla: yes, size/M

#153 Return sender with actionable messages
  src/main/java/com/google/sps/model/ActionableMessage.java
  src/main/java/com/google/sps/model/GmailResponseHelperImpl.java
  src/main/java/com/google/sps/servlets/GmailActionableEmailsServlet.java
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/test/java/GmailActionableEmailsServletTest.java
  src/test/java/GmailUtilityTest.java
Labels: cla: yes, size/L

#137 Working version of the assign panel
  README.md
  src/main/webapp/assignPanel.js
  src/main/webapp/assignPanelStyle.js
  src/main/webapp/index.html
  src/main/webapp/panelStyle.js
  src/main/webapp/populateData.js
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/abstracts/_variables.css
  src/main/webapp/style/base/_typography.css
  src/main/webapp/style/components/_button-circle.css
  src/main/webapp/style/components/_panel.css
  src/main/webapp/task.js
Labels: cla: yes, size/XL

#142 Use batching to more efficiently handle large volumes of Gmail requests
  src/main/java/com/google/sps/exceptions/GmailException.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
Labels: cla: yes, size/L

#146 Refactor Tasks for Go panel
  src/main/java/com/google/sps/model/PlacesClientImpl.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/TasksUtility.java
  src/test/java/PlacesClientTest.java
  src/test/java/TasksUtilityTest.java
Labels: cla: yes, size/L

#141 Add settings for Gmail panel
  src/main/webapp/assignPanelStyle.js
  src/main/webapp/gmailPanel.js
  src/main/webapp/gmailPanelStyle.js
  src/main/webapp/index.html
  src/main/webapp/panelStyle.js
  src/main/webapp/populateData.js
  src/main/webapp/style/components/_panel.css
Labels: cla: yes, size/L

#155 Refactor the Gmail Utility to check if a header is present without throwing error
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/test/java/GmailUtilityTest.java
Labels: cla: yes, size/M

#147 Add methods to Locations Utility for Go panel
  src/main/java/com/google/sps/utility/LocationsUtility.java
  src/test/java/LocationsUtilityTest.java
  src/test/java/TasksUtilityTest.java
Labels: cla: yes, size/M

#131 Implement Go servlet
  src/main/java/com/google/sps/servlets/GoServlet.java
  src/main/java/com/google/sps/utility/GeocodingResultUtility.java
  src/test/java/GoServletTest.java
Labels: cla: yes, size/XL

#149 Implement client side for Go panel
  src/main/java/com/google/sps/servlets/GoServlet.java
  src/main/webapp/assets/maps.png
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/components/_button-1-of-1.css
Labels: cla: yes, size/L

#150 Implement post request with plan-mail
  src/main/java/com/google/sps/data/PlanMailResponse.java
  src/main/java/com/google/sps/model/CalendarClient.java
  src/main/java/com/google/sps/model/CalendarClientImpl.java
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/servlets/PlanMailServlet.java
  src/main/webapp/index.html
  src/main/webapp/populateData.js
Labels: cla: yes, enhancement, size/L

#156 README for updating instructions
  README.md
  blueprint.png
Labels: cla: yes, size/L

#151 Implement UI design for the plan mail panel
  src/main/webapp/assets/back_arrow.png
  src/main/webapp/assets/plan_tick.png
  src/main/webapp/index.html
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/abstracts/_variables.css
Labels: cla: yes, enhancement, size/M

#129 Implementation of Get request for the plan-mail feature
  src/main/java/com/google/sps/data/PlanMailResponse.java
  src/main/java/com/google/sps/model/CalendarClient.java
  src/main/java/com/google/sps/model/CalendarClientImpl.java
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/servlets/PlanMailServlet.java
  src/main/java/com/google/sps/utility/FreeTimeUtility.java
  src/main/webapp/assets/back_arrow.png
  src/main/webapp/assets/plan_tick.png
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/abstracts/_variables.css
  src/test/java/CalendarServletTest.java
Labels: cla: yes, enhancement, size/XL
