Repository googleinterns/blueprint-step-2020, pull requests merged in 2020-07, with the labels that each got.

#34 Add size label action
  .github/workflows/size-label.yml
Labels: size/S

#21 Feature/gmail utility
  pom.xml
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/AuthenticationUtility.java
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/main/java/com/google/sps/utility/TasksUtility.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/GmailUtilityTest.java
Labels: size/XL

#20 Prototype/authentication with java library
  pom.xml
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/AuthenticationUtility.java
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/main/java/com/google/sps/utility/TasksUtility.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/AuthenticationUtilityTest.java
  src/test/java/GmailUtilityTest.java
Labels: size/XL

#49 Refactor existing style to conform with 7:1 principle of file hierarchy
  src/main/webapp/index.html
  src/main/webapp/style/abstracts/_variables.css
  src/main/webapp/style/layout/_layout.css
Labels: size/XS

#54 Create abstract class to handle authentication verification/errors
  src/main/java/com/google/sps/model/AuthenticatedHttpServlet.java
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/AuthenticationUtility.java
Labels: cla: yes, size/L

#55 Create Servlet Utility to handle common Servlet operations
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/AuthenticationUtility.java
  src/main/java/com/google/sps/utility/GmailUtility.java
  src/main/java/com/google/sps/utility/ServletUtility.java
  src/main/java/com/google/sps/utility/TasksUtility.java
  src/test/java/AuthenticationUtilityTest.java
  src/test/java/ServletUtilityTest.java
Labels: cla: yes, size/L

#73 Add config for Stylelint
  .github/linters/.stylelintrc.json
Labels: cla: yes, size/XS

#57 Initial implementation of calendar utility
  pom.xml
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/utility/CalendarUtility.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/script.js
Labels: cla: yes, size/L

#71 Refactor tasks to use client abstraction pattern
  src/main/java/com/google/sps/model/TasksClient.java
  src/main/java/com/google/sps/model/TasksClientFactory.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#70 Refactor gmail to use client abstraction pattern
  src/main/java/com/google/sps/model/GmailClient.java
  src/main/java/com/google/sps/model/GmailClientFactory.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/test/java/GmailClientTest.java
  src/test/java/GmailServletTest.java
Labels: cla: yes, size/L

#69 Refactor authentication to use client abstraction pattern
  pom.xml
  src/main/java/com/google/sps/exceptions/CookieParseException.java
  src/main/java/com/google/sps/exceptions/CredentialVerificationException.java
  src/main/java/com/google/sps/model/AuthenticatedHttpServlet.java
  src/main/java/com/google/sps/model/AuthenticationVerifier.java
  src/main/java/com/google/sps/model/AuthenticationVerifierImpl.java
  src/main/java/com/google/sps/model/GmailClient.java
  src/main/java/com/google/sps/model/GmailClientFactory.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
  src/main/java/com/google/sps/model/TasksClient.java
  src/main/java/com/google/sps/model/TasksClientFactory.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/servlets/ClientIDServlet.java
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/AuthenticationUtility.java
  src/main/java/com/google/sps/utility/ServletUtility.java
  src/test/java/AuthenticatedHttpServletTest.java
  src/test/java/AuthenticationUtilityTest.java
  src/test/java/ClientIDServletTest.java
  src/test/java/GmailClientTest.java
  src/test/java/GmailServletTest.java
  src/test/java/ServletUtilityTest.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/XXL

#51 Handle fetching keys from Secret Manager
  .gitignore
  cloudbuild.yaml
  pom.xml
  src/main/java/com/google/sps/utility/KeyProvider.java
  src/test/java/KeyProviderTest.java
Labels: cla: yes, size/L

#89 Control deployment promotion via trigger variable
  cloudbuild.yaml
Labels: cla: yes, size/XS

#40 Implement JSON utility class
  pom.xml
  src/main/java/com/google/sps/utility/JsonUtility.java
  src/test/java/JsonUtilityTest.java
Labels: cla: yes, enhancement, size/L

#91 Implement JSON utility class (Remerge of #40)
  pom.xml
  src/main/java/com/google/sps/utility/JsonUtility.java
  src/test/java/JsonUtilityTest.java
Labels: cla: yes, size/L

#90 Fix throws list on doGet and doPost
  src/main/java/com/google/sps/model/AuthenticatedHttpServlet.java
Labels: cla: yes, size/S

#93 Use stringbuilder for multiple part query string
  src/main/java/com/google/sps/model/GmailClient.java
Labels: cla: yes, size/S

#80 Refactor calendar utility
  src/main/java/com/google/sps/model/CalendarClient.java
  src/main/java/com/google/sps/model/CalendarClientFactory.java
  src/main/java/com/google/sps/model/CalendarClientImpl.java
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/utility/CalendarUtility.java
  src/test/java/CalendarServletTest.java
Labels: cla: yes, size/L

#87 Refactor u-vertical-center
  src/main/webapp/index.html
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/components/_panel.css
Labels: cla: yes, size/M

#86 Create MVP version of Gmail Panel
  src/main/java/com/google/sps/exceptions/GmailMessageFormatException.java
  src/main/java/com/google/sps/model/GmailClient.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
  src/main/java/com/google/sps/model/GmailResponse.java
  src/main/java/com/google/sps/model/GmailResponseHelper.java
  src/main/java/com/google/sps/model/GmailResponseHelperImpl.java
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/style/abstracts/_utilities.css
  src/main/webapp/style/components/_panel.css
  src/test/java/GmailClientTest.java
  src/test/java/GmailResponseHelperImplTest.java
  src/test/java/GmailServletTest.java
  src/test/java/GmailTestBase.java
  src/test/java/HttpServletResponseFake.java
  src/test/java/JsonUtilityTest.java
Labels: cla: yes, size/XXL

#88 Create MVP version of Tasks Panel
  src/main/java/com/google/sps/model/TasksClient.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/model/TasksResponse.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#63 Refactor Directions utility for dependency injection
  pom.xml
  src/main/java/com/google/sps/exceptions/DirectionsException.java
  src/main/java/com/google/sps/model/DirectionsClient.java
  src/main/java/com/google/sps/model/DirectionsClientFactory.java
  src/main/java/com/google/sps/model/DirectionsClientImpl.java
  src/main/java/com/google/sps/servlets/DirectionsServlet.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/DirectionsClientImplTest.java
  src/test/java/DirectionsServletTest.java
  src/test/java/JsonUtilityTest.java
Labels: cla: yes, size/XL

#106 Create superclasses for testing servlets
  src/test/java/AuthenticatedHttpServletTest.java
  src/test/java/AuthenticatedServletTestBase.java
  src/test/java/CalendarServletTest.java
  src/test/java/ClientIDServletTest.java
  src/test/java/GmailClientTest.java
  src/test/java/GmailResponseHelperImplTest.java
  src/test/java/GmailServletTest.java
  src/test/java/GmailTestBase.java
  src/test/java/HttpServletResponseFake.java
  src/test/java/JsonUtilityTest.java
  src/test/java/KeyProviderTest.java
  src/test/java/ServletTestBase.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#102 Create functionality for posting/getting tasklists
  src/main/java/com/google/sps/model/GmailResponseHelperImpl.java
  src/main/java/com/google/sps/model/TasksClient.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/servlets/TaskListServlet.java
  src/main/java/com/google/sps/utility/JsonUtility.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/utilities.js
  src/test/java/TaskListServletTest.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/XL

#111 Bug fixes Gmail Servlet
  src/main/java/com/google/sps/servlets/GmailServlet.java
  src/test/java/GmailServletTest.java
Labels: bug, cla: yes, size/S

#113 Remove GmailTestBase
  src/test/java/GmailResponseHelperImplTest.java
  src/test/java/GmailServletTest.java
  src/test/java/GmailTestBase.java
Labels: bug, cla: yes, size/L

#103 Allow for posting new tasks to user's account
  src/main/java/com/google/sps/model/TasksClient.java
  src/main/java/com/google/sps/model/TasksClientImpl.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/main/webapp/task.js
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#110 Update GmailClient query string methods
  src/main/java/com/google/sps/model/GmailClient.java
  src/main/java/com/google/sps/model/GmailClientImpl.java
  src/test/java/GmailClientTest.java
Labels: cla: yes, size/L

#105 Refactor Tasks panel
  pom.xml
  src/main/java/com/google/sps/model/TasksResponse.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#120 Comment out postAndGetTaskList
  src/main/webapp/auth.js
Labels: cla: yes, size/XS

#108 Refactor master to use JsonUtility and KeyProvider
  src/main/java/com/google/sps/model/AuthenticationVerifier.java
  src/main/java/com/google/sps/model/AuthenticationVerifierImpl.java
  src/main/java/com/google/sps/servlets/CalendarServlet.java
  src/main/java/com/google/sps/servlets/ClientIDServlet.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/java/com/google/sps/utility/KeyProvider.java
  src/main/webapp/auth.js
  src/test/java/ClientIDServletTest.java
Labels: cla: yes, size/M

#126 Fix variables names in populateTasks
  src/main/webapp/populateData.js
Labels: bug, cla: yes, size/XS

#116 Implement Places Client
  src/main/java/com/google/sps/exceptions/PlacesException.java
  src/main/java/com/google/sps/model/PlacesClient.java
  src/main/java/com/google/sps/model/PlacesClientFactory.java
  src/main/java/com/google/sps/model/PlacesClientImpl.java
  src/test/java/PlacesClientImplTest.java
Labels: cla: yes, size/L

#114 Add task list selection to Tasks panel
  src/main/java/com/google/sps/model/TasksResponse.java
  src/main/java/com/google/sps/servlets/TasksServlet.java
  src/main/webapp/auth.js
  src/main/webapp/index.html
  src/main/webapp/populateData.js
  src/test/java/TasksServletTest.java
Labels: cla: yes, size/L

#127 Fix authentication in deployed server
  src/main/java/com/google/sps/utility/KeyProvider.java
  src/test/java/KeyProviderTest.java
Labels: bug, cla: yes, size/L
